cmd_help() {
  echo -e "Usage: ${GR}ncli${NC} ${YE}[subcommand]${NC}"
  echo ""
  echo "Available subcommands:"
  echo -e "  ${GR}help${NC}                          Show this help"
  echo -e "  ${GR}build${NC}                         nh os build"
  echo -e "  ${GR}switch${NC}                        nh os switch"
  echo -e "  ${GR}boot${NC}                          nh os boot"
  echo -e "  ${GR}test${NC}                          nh os test"
  echo -e "  ${GR}update${NC}                        nh os switch -u"
  echo -e "  ${GR}clean${NC}                         nh clean all --keep 8"
  echo -e "  ${GR}fmt${NC}                           nix fmt"
  echo -e "  ${GR}search${NC} ${YE}<pkg>${NC}                  nix search nixpkgs <pkg>"
  echo -e "  ${GR}run${NC} ${YE}<pkg>${NC}                     nix run nixpkgs#<pkg>"
  echo -e "  ${GR}shell${NC} ${YE}<pkg>${NC}                   nix shell nixpkgs#<pkg>"
  echo -e "  ${GR}generations${NC}                   List system generations"
  echo -e "  ${GR}module list${NC} ${YE}[host]${NC}            List modules enabled/disabled on a host"
  echo -e "  ${GR}module enable${NC} ${YE}<name> [host]${NC}   Enable a module on a host"
  echo -e "  ${GR}module disable${NC} ${YE}<name> [host]${NC}  Disable a module on a host"
}
cmd_help "$@"
