#!/usr/bin/env bash
set -euo pipefail

NCLI_DIR="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)"
export NCLI_DIR

source "$NCLI_DIR/ncli.lib/index.sh"

cmd="${1:-help}"; shift || true
case "$cmd" in
  build|boot|switch|test|update)
    source "$NCLI_DIR/ncli.cmds/rebuild.sh" "$cmd" "$@"
    ;;
  *)
    cmd_path="$NCLI_DIR/ncli.cmds/${cmd}.sh"
    if [ -f "$cmd_path" ]; then
      source "$cmd_path" "$@"
    else
      error "Unknown subcommand: $cmd. Run 'ncli help'."
    fi
    ;;
esac
