#!/usr/bin/env bash
# Quickshell Debugger
# Restarts Quickshell with Advanced Debugging.

notify() {
    if command -v notify-send >/dev/null; then
        notify-send "Quickshell Debug" "$1" \
            --app-name="Quickshell" \
            --icon="utilities-terminal" \
            --urgency=low
    fi
}

echo "Stopping Quickshell service..."
systemctl --user stop quickshell.service

notify "Starting debug mode..."
echo "Starting Quickshell in foreground..."
echo "-----------------------------------"

QT_USE_PORTAL=1 quickshell

echo "-----------------------------------"
echo "Restarting background service..."
systemctl --user start quickshell.service
