#!/usr/bin/env bash
# Restarts Quickshell

notify() {
    if command -v notify-send >/dev/null; then
        notify-send "Quickshell" "$1" \
            --app-name="Quickshell" \
            --icon="system-software-update" \
            --urgency=low
    fi
}

echo "Restarting Quickshell service..."
systemctl --user restart quickshell.service

if [ $? -eq 0 ]; then
    notify "Shell restarted successfully"
    echo "Done."
else
    notify "Failed to restart Shell"
    echo "Error: Failed to restart quickshell.service"
    exit 1
fi
