cmd_help() {
  echo "dcli — declarative cli for NixOS flake management"
  echo ""
  echo "Usage: dcli [subcommand]"
  echo ""
  echo "Available subcommands:"
  echo "  help         Show this help"
  echo "  rebuild      nh os switch"
  echo "  test         nh os test"
  echo "  update       nh os switch -u"
  echo "  gc           nh clean all --keep 8"
  echo "  generations  List system generations"
  echo "  fmt          nix fmt"
  echo "  search <pkg> nix search nixpkgs <pkg>"
  echo "  module list [host]  List modules enabled/disabled on a host"
  echo "  version             Show repo HEAD and flake.lock mtime"
  echo ""
  echo "Run 'dcli' without arguments for the interactive menu."
}
cmd_help "$@"
