# This is a placeholder.
# Overwrite this file with the one generated by the NixOS installer
# (/etc/nixos/hardware-configuration.nix) inside the VMware VM.

{ ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "mptspi"
    "uhci_hcd"
    "ehci_pci"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/sda1"; # Dummy value
    fsType = "ext4";
  };

  swapDevices = [ ];
}
